# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [33]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/goran/new anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/goran/new anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/goran/new anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/goran/new anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/goran/new anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/goran/new anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/goran/new anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/goran/new anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [8]:
np.zeros([1,10])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4.  How to find the memory size of any array

In [9]:
np.size

<function numpy.size(a, axis=None)>

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [35]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [39]:
a = np.zeros(10)
a[4] = 1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [15]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [44]:
b = np.arange(0,15)
print(b)
c = b[::-1]
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
c = np.arange(0, 9)
b = c.reshape((3, 3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [46]:
arr = np.array([1,2,0,0,4,0])
c= np.nonzero(arr)
c

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [50]:
x = np.random.random((3,3,3))
x

array([[[0.68578807, 0.9630015 , 0.04446409],
        [0.25342299, 0.07036206, 0.4188247 ],
        [0.63706805, 0.4258846 , 0.51353166]],

       [[0.80316621, 0.27022475, 0.52920738],
        [0.57094653, 0.22371519, 0.68108261],
        [0.63536853, 0.99783377, 0.3031224 ]],

       [[0.75364186, 0.65451861, 0.67079201],
        [0.4177058 , 0.6437398 , 0.80428734],
        [0.97814258, 0.08539281, 0.87204897]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [55]:
x= np.random.random((10,10))
print(x)
print(x.max())
print(x.min())

[[0.99818612 0.75665412 0.32790479 0.84319211 0.78993223 0.50652713
  0.81050977 0.86368387 0.39663417 0.8442343 ]
 [0.97688154 0.21731602 0.46909831 0.12242199 0.00318842 0.1593241
  0.34640046 0.31252694 0.96912995 0.66069912]
 [0.72823792 0.47819835 0.97708615 0.77587623 0.27691631 0.27928982
  0.15347712 0.25768168 0.44144122 0.51493116]
 [0.92518508 0.2440488  0.0675204  0.47252625 0.70798256 0.55289538
  0.56256912 0.97090237 0.8729195  0.93432156]
 [0.43447028 0.34129326 0.52665741 0.47435827 0.57097876 0.16839947
  0.2603796  0.72653914 0.21245273 0.90908295]
 [0.17033626 0.6450939  0.09923626 0.01856566 0.80596815 0.91516402
  0.03009886 0.41682106 0.56077773 0.63775079]
 [0.34334862 0.66662665 0.57855354 0.08999444 0.84550347 0.10825137
  0.48464309 0.56414609 0.18371273 0.76386419]
 [0.25944735 0.47271139 0.57047104 0.75831402 0.13349679 0.32021979
  0.17103917 0.67670807 0.16715737 0.38502167]
 [0.3085301  0.05230628 0.72646264 0.70060834 0.46368394 0.51565444
  0.85860313 

#### 14. Create a random vector of size 30 and find the mean value

In [59]:
a = np.random.random(30)
print(a)
print(a.mean())


[0.17179795 0.2049379  0.02762923 0.95120386 0.6812098  0.53546847
 0.66538584 0.67481012 0.29125925 0.44316173 0.20237839 0.5237038
 0.03967849 0.89331076 0.75926524 0.89468497 0.17273955 0.95374953
 0.49211703 0.24479049 0.92164239 0.5558487  0.65442117 0.85306677
 0.58557587 0.37741578 0.2678506  0.62033765 0.25543282 0.1433957 ]
0.5019423288625046


#### 15. Create a 2d array with 1 on the border and 0 inside

In [62]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

SyntaxError: invalid syntax (<ipython-input-65-61a11fffcd06>, line 1)

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [74]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [68]:
x= np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [73]:
y = np.unravel_index(100, (6,7,8))
y

(1, 5, 4)